kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ha2
loadBalancer:
  dockerIP: ha2-external-load-balancer
nodes:
  - role: control-plane
    dockerIP: ha2-control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=false"
  - role: control-plane
    dockerIP: ha2-control-plane2
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=false"
  - role: control-plane
    dockerIP: ha2-control-plane3
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=false"
  - role: worker
    dockerIP: ha2-worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  - role: worker
    dockerIP: ha2-worker2
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
